In [1]:
import pandas as pd

In [2]:
orders = pd.read_csv("data/olist_orders_dataset.csv")
orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [3]:
orders.shape

(99441, 8)

In [4]:
orders.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [5]:
orders["order_status"].value_counts()

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

In [6]:
orders.duplicated().sum()

np.int64(0)

In [8]:
canceled = orders[orders["order_status"] == "canceled"]
canceled.isnull().sum()

order_id                           0
customer_id                        0
order_status                       0
order_purchase_timestamp           0
order_approved_at                141
order_delivered_carrier_date     550
order_delivered_customer_date    619
order_estimated_delivery_date      0
dtype: int64

In [12]:
delivered = orders[orders["order_status"] == "delivered"]
delivered.shape

(96478, 8)

In [13]:
canceled = orders[orders["order_status"] == "canceled"]
canceled.isnull().sum()

order_id                           0
customer_id                        0
order_status                       0
order_purchase_timestamp           0
order_approved_at                141
order_delivered_carrier_date     550
order_delivered_customer_date    619
order_estimated_delivery_date      0
dtype: int64

In [16]:
items = pd.read_csv("data/olist_order_items_dataset.csv")
customers = pd.read_csv("data/olist_customers_dataset.csv")

In [17]:
items.shape

(112650, 7)

In [18]:
items.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [19]:
customers.shape

(99441, 5)

In [20]:
customers.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [23]:
df = pd.merge(delivered, items, on="order_id")

In [22]:
df.shape

(110197, 14)

In [24]:
df["order_id"].nunique()

96478

In [25]:
df["price"].sum()

np.float64(13221498.110000001)

In [2]:
import pandas as pd

orders = pd.read_csv("data/olist_orders_dataset.csv")
items = pd.read_csv("data/olist_order_items_dataset.csv")
customers = pd.read_csv("data/olist_customers_dataset.csv")

delivered = orders[orders["order_status"] == "delivered"]
df = pd.merge(delivered, items, on="order_id")
df.shape

(110197, 14)

In [3]:
df["price"].sum() / df["order_id"].nunique()

np.float64(137.04158575011922)

In [5]:
df = pd.merge(df, customers, on="customer_id")

In [6]:
df.shape

(110197, 18)

In [7]:
df["price"].sum() / df["order_id"].nunique()

np.float64(137.04158575011922)

In [8]:
df ["customer_unique_id"].nunique()

93358

In [10]:
orders_per_customer = df.groupby("customer_unique_id")["order_id"].nunique()
orders_per_customer.head()

customer_unique_id
0000366f3b9a7992bf8c76cfdf3221e2    1
0000b849f77a49e4a4ce2b2a4ca5be3f    1
0000f46a3911fa3c0805444483337064    1
0000f6ccb0745a6a4b88665a16c9f078    1
0004aac84e0df4da2b147fca70cf8255    1
Name: order_id, dtype: int64

In [11]:
repeat_customers = (orders_per_customer > 1).sum()
total_customers =df["customer_unique_id"].nunique()
repeat_rate = repeat_customers/ total_customers * 100
repeat_rate

np.float64(3.0002784978255748)

In [13]:
products = pd.read_csv("data/olist_products_dataset.csv")
translation = pd.read_csv("data/product_category_name_translation.csv")

In [14]:
products.head()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

In [15]:
translation.head()

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

In [16]:
df = pd.merge(df, products[["product_id", "product_category_name"]], on="product_id", how="left")

In [17]:
df = pd.merge(df, translation, on="product_category_name", how="left")

In [18]:
df.shape

(110197, 20)

In [19]:
df["product_category_name_english"].isnull().sum()

np.int64(1559)

In [20]:
df["product_category_name_english"].fillna("unknown")

0                    housewares
1                     perfumery
2                          auto
3                      pet_shop
4                    stationery
                  ...
110192                     baby
110193        home_appliances_2
110194    computers_accessories
110195    computers_accessories
110196            health_beauty
Name: product_category_name_english, Length: 110197, dtype: str

In [1]:
df["product_category_name_english"] = df["product_category_name_english"].fillna("unknown")

NameError: name 'df' is not defined

In [2]:
import pandas as pd

orders = pd.read_csv("data/olist_orders_dataset.csv")
items = pd.read_csv("data/olist_order_items_dataset.csv")
customers = pd.read_csv("data/olist_customers_dataset.csv")
products = pd.read_csv("data/olist_products_dataset.csv")
translation = pd.read_csv("data/product_category_name_translation.csv")

delivered = orders[orders["order_status"] == "delivered"]
df = pd.merge(delivered, items, on="order_id")
df = pd.merge(df, customers, on="customer_id")
df = pd.merge(df, products[["product_id", "product_category_name"]], on="product_id", how="left")
df = pd.merge(df, translation, on="product_category_name", how="left")
df["product_category_name_english"] = df["product_category_name_english"].fillna("unknown")
df.shape

(110197, 20)

In [3]:
df["product_category_name_english"].isnull().sum()

np.int64(0)

In [5]:
df.groupby("product_category_name_english")["price"].sum().sort_values(ascending=False).head(10)

product_category_name_english
health_beauty            1233131.72
watches_gifts            1166176.98
bed_bath_table           1023434.76
sports_leisure            954852.55
computers_accessories     888724.61
furniture_decor           711927.69
housewares                615628.69
cool_stuff                610204.10
auto                      578966.65
toys                      471286.48
Name: price, dtype: float64

In [7]:
df.groupby("product_category_name_english")["price"].sum().sort_values(ascending=True).head(10)

product_category_name_english
security_and_services         283.29
fashion_childrens_clothes     519.95
cds_dvds_musicals             730.00
home_comfort_2                760.27
flowers                      1110.04
diapers_and_hygiene          1500.79
arts_and_craftmanship        1814.01
la_cuisine                   2054.99
fashion_sport                2094.52
fashio_female_clothing       2634.94
Name: price, dtype: float64

In [8]:
df.groupby("product_category_name_english")["order_id"].nunique().sort_values(ascending=False).head(10)

product_category_name_english
bed_bath_table           9272
health_beauty            8647
sports_leisure           7530
computers_accessories    6530
furniture_decor          6307
housewares               5743
watches_gifts            5495
telephony                4093
auto                     3810
toys                     3804
Name: order_id, dtype: int64

In [9]:
cat = df.groupby("product_category_name_english").agg(
    revenue=("price", "sum"),
    orders=("order_id", "nunique")
)
cat["avg_price_per_order"] = cat["revenue"] / cat["orders"]

In [10]:
cat.sort_values("revenue", ascending=False).head(10)

                                  revenue  orders  avg_price_per_order
product_category_name_english
health_beauty                  1233131.72    8647           142.608040
watches_gifts                  1166176.98    5495           212.225110
bed_bath_table                 1023434.76    9272           110.379072
sports_leisure                  954852.55    7530           126.806448
computers_accessories           888724.61    6530           136.098715
furniture_decor                 711927.69    6307           112.878974
housewares                      615628.69    5743           107.196359
cool_stuff                      610204.10    3559           171.453807
auto                            578966.65    3810           151.959751
toys                            471286.48    3804           123.892345

In [11]:
cat.sort_values("avg_price_per_order", ascending=False).head(10)

                                         revenue  orders  avg_price_per_order
product_category_name_english
computers                              218684.14     177          1235.503616
small_appliances_home_oven_and_coffee   46589.56      72           647.077222
home_appliances_2                      107953.95     227           475.568062
agro_industry_and_commerce              70566.10     177           398.678531
musical_instruments                    184315.74     611           301.662422
small_appliances                       182754.12     609           300.088867
fixed_telephony                         55315.21     212           260.920802
construction_tools_safety               38773.22     159           243.856730
air_conditioning                        53323.56     246           216.762439
office_furniture                       268154.31    1254           213.839163

In [12]:
cat[cat["orders"] >= 100].sort_values("avg_price_per_order", ascending=False).head(10)

                                  revenue  orders  avg_price_per_order
product_category_name_english
computers                       218684.14     177          1235.503616
home_appliances_2               107953.95     227           475.568062
agro_industry_and_commerce       70566.10     177           398.678531
musical_instruments             184315.74     611           301.662422
small_appliances                182754.12     609           300.088867
fixed_telephony                  55315.21     212           260.920802
construction_tools_safety        38773.22     159           243.856730
air_conditioning                 53323.56     246           216.762439
office_furniture                268154.31    1254           213.839163
watches_gifts                  1166176.98    5495           212.225110

In [1]:
import pandas as pd

orders = pd.read_csv("data/olist_orders_dataset.csv")
items = pd.read_csv("data/olist_order_items_dataset.csv")
customers = pd.read_csv("data/olist_customers_dataset.csv")
products = pd.read_csv("data/olist_products_dataset.csv")
translation = pd.read_csv("data/product_category_name_translation.csv")

delivered = orders[orders["order_status"] == "delivered"]
df = pd.merge(delivered, items, on="order_id")
df = pd.merge(df, customers, on="customer_id")
df = pd.merge(df, products[["product_id", "product_category_name"]], on="product_id", how="left")
df = pd.merge(df, translation, on="product_category_name", how="left")
df["product_category_name_english"] = df["product_category_name_english"].fillna("unknown")
df.shape

(110197, 20)

In [3]:
df["order_purchase_timestamp"] = pd.to_datetime(df["order_purchase_timestamp"])
df["Month"] = df["order_purchase_timestamp"].dt.to_period("M")

In [5]:
Monthly = df.groupby("Month").agg(
    revenue=("price", "sum"),
    orders=("order_id", "nunique")
)
Monthly["aov"] = Monthly["revenue"] / Monthly["orders"]
Monthly

           revenue  orders         aov
Month
2016-09     134.97       1  134.970000
2016-10   40325.11     265  152.170226
2016-12      10.90       1   10.900000
2017-01  111798.36     750  149.064480
2017-02  234223.40    1653  141.695947
2017-03  359198.85    2546  141.083602
2017-04  340669.68    2303  147.924307
2017-05  489338.25    3546  137.997250
2017-06  421923.37    3135  134.584807
2017-07  481604.52    3872  124.381333
2017-08  554699.70    4193  132.291844
2017-09  607399.67    4150  146.361366
2017-10  648247.65    4478  144.762762
2017-11  987765.37    7289  135.514525
2017-12  726033.19    5513  131.694756
2018-01  924645.00    7069  130.802801
2018-02  826437.13    6555  126.077365
2018-03  953356.25    7003  136.135406
2018-04  973534.09    6798  143.208898
2018-05  977544.69    6749  144.842894
2018-06  856077.86    6099  140.363643
2018-07  867953.46    6159  140.924413
2018-08  838576.64    6351  132.038520

In [13]:
import plotly.express as px

In [15]:
plot_df = Monthly.reset_index()
plot_df["Month"] = plot_df["Month"].astype(str)
plot_df = plot_df[plot_df["Month"] >= "2017-01"]

fig = px.line(plot_df, x="Month", y="revenue", title="Monthly Revenue", markers=True)
fig

In [16]:
fig.show(renderer="browser")

In [17]:
Monthly["revenue"].idxmax()

Period('2017-11', 'M')

In [18]:
growth = Monthly.loc["2017-01":, "revenue"].pct_change() * 100
growth.round(1)

Month
2017-01      NaN
2017-02    109.5
2017-03     53.4
2017-04     -5.2
2017-05     43.6
2017-06    -13.8
2017-07     14.1
2017-08     15.2
2017-09      9.5
2017-10      6.7
2017-11     52.4
2017-12    -26.5
2018-01     27.4
2018-02    -10.6
2018-03     15.4
2018-04      2.1
2018-05      0.4
2018-06    -12.4
2018-07      1.4
2018-08     -3.4
Freq: M, Name: revenue, dtype: float64

In [20]:
state = df.groupby("customer_state").agg(
    revenue=("price", "sum"),
    orders=("order_id", "nunique")
)
state["avg_price_per_order"] = state["revenue"] / state["orders"]
state["share_pct"] = state["revenue"] / state["revenue"].sum() * 100

In [21]:
state.sort_values("revenue", ascending=False).round(1).head(10)

                  revenue  orders  avg_price_per_order  share_pct
customer_state
SP              5067633.2   40501                125.1       38.3
RJ              1759651.1   12350                142.5       13.3
MG              1552481.8   11354                136.7       11.7
RS               728897.5    5345                136.4        5.5
PR               666063.5    4923                135.3        5.0
SC               507012.1    3546                143.0        3.8
BA               493584.1    3256                151.6        3.7
DF               296498.4    2080                142.5        2.2
GO               282836.7    1957                144.5        2.1
ES               268643.4    1995                134.7        2.0

In [23]:
state.sort_values("revenue", ascending=False).round(1).tail(10)

                revenue  orders  avg_price_per_order  share_pct
customer_state
PI              84721.0     476                178.0        0.6
RN              82105.7     474                173.2        0.6
AL              78855.7     397                198.6        0.6
SE              56574.2     335                168.9        0.4
TO              48402.5     274                176.7        0.4
RO              45682.8     243                188.0        0.3
AM              22155.8     145                152.8        0.2
AC              15931.0      80                199.1        0.1
AP              13374.8      67                199.6        0.1
RR               7057.5      41                172.1        0.1

In [24]:
state.sort_values("revenue", ascending=False).round(1).tail(10)

                revenue  orders  avg_price_per_order  share_pct
customer_state
PI              84721.0     476                178.0        0.6
RN              82105.7     474                173.2        0.6
AL              78855.7     397                198.6        0.6
SE              56574.2     335                168.9        0.4
TO              48402.5     274                176.7        0.4
RO              45682.8     243                188.0        0.3
AM              22155.8     145                152.8        0.2
AC              15931.0      80                199.1        0.1
AP              13374.8      67                199.6        0.1
RR               7057.5      41                172.1        0.1

In [25]:
cust = df.groupby("customer_unique_id").agg(
    revenue=("price", "sum"),
    orders=("order_id", "nunique")
)
cust.sort_values("revenue", ascending=False).round(1).head(10)

                                  revenue  orders
customer_unique_id
0a0a92112bd4c708ca5fde585afaa872  13440.0       1
da122df9eeddfedc1dc1f5349a1a690c   7388.0       2
763c8b1c9c68a0229c42c9fc6f662b93   7160.0       1
dc4802a71eae9be1dd28f5d788ceb526   6735.0       1
459bef486812aa25204be022145caa62   6729.0       1
ff4159b92c40ebe40454e3e6a7c35ed6   6499.0       1
4007669dec559734d6f53e029e360987   5934.6       1
eebb5dda148d3893cdaf5b5ca3040ccb   4690.0       1
48e1ac109decbb87765a3eade6854098   4590.0       1
a229eba70ec1c2abef51f04987deb7a5   4400.0       1

In [26]:
sorted_rev =cust["revenue"].sort_values(ascending=False)
top_n = int(len(sorted_rev) * 0.1)
sorted_rev.head(top_n).sum() / sorted_rev.sum() * 100

np.float64(41.09779803160293)

In [31]:
df["cohort_month"] = df.groupby("customer_unique_id")["order_purchase_timestamp"].transform("min").dt.to_period("M")

In [32]:
df["months_since"] = (df["Month"].dt.year - df["cohort_month"].dt.year) * 12 + (df["Month"].dt.month - df["cohort_month"].dt.month)

In [33]:
df[["customer_unique_id", "Month", "cohort_month", "months_since"]].head(10)

                 customer_unique_id    Month cohort_month  months_since
0  7c396fd4830fd04220f754e42b4e5bff  2017-10      2017-09             1
1  af07308b275d755c9edb36a90c618231  2018-07      2018-07             0
2  3a653a41f6f9fc3d2a113cf8398680e8  2018-08      2018-08             0
3  7c142cf63193a1473d2e66489a9ae977  2017-11      2017-11             0
4  72632f0f9dd73dfee390c9b22eb56dd6  2018-02      2018-02             0
5  80bb27c7c16e8f973207a5086ab329e2  2017-07      2017-07             0
6  932afa1e708222e5821dac9cd5db4cae  2017-05      2017-05             0
7  39382392765b6dc74812866ee5ee92a7  2017-01      2017-01             0
8  299905e3934e9e181bfb2e164dd4b4f8  2017-07      2017-07             0
9  f2a85dec752b8517b5e58a06ff3cd937  2017-05      2017-05             0

In [34]:
df["months_since"].max()

np.int64(20)

In [35]:
df.shape

(110197, 23)

In [36]:
cohort = df.groupby(["cohort_month", "months_since"])["customer_unique_id"].nunique().reset_index()
cohort.head()

  cohort_month  months_since  customer_unique_id
0      2016-09             0                   1
1      2016-10             0                 262
2      2016-10             6                   1
3      2016-10             9                   1
4      2016-10            11                   1

In [37]:
cohort_table = cohort.pivot_table(index="cohort_month", columns="months_since", values="customer_unique_id")
cohort_table.iloc[:6, :6]

months_since       0     1    2     3    4    5
cohort_month
2016-09          1.0   NaN  NaN   NaN  NaN  NaN
2016-10        262.0   NaN  NaN   NaN  NaN  NaN
2016-12          1.0   1.0  NaN   NaN  NaN  NaN
2017-01        717.0   2.0  2.0   1.0  3.0  1.0
2017-02       1628.0   3.0  5.0   2.0  7.0  2.0
2017-03       2503.0  11.0  9.0  10.0  9.0  4.0

In [38]:
cohort_size = cohort_table[0]
retention = cohort_table.divide(cohort_size, axis=0) * 100
retention = retention.loc["2017-01":]
retention.round(1).iloc[:8, :8]

months_since      0    1    2    3    4    5    6    7
cohort_month
2017-01       100.0  0.3  0.3  0.1  0.4  0.1  0.4  0.1
2017-02       100.0  0.2  0.3  0.1  0.4  0.1  0.2  0.2
2017-03       100.0  0.4  0.4  0.4  0.4  0.2  0.2  0.3
2017-04       100.0  0.6  0.2  0.2  0.3  0.3  0.4  0.3
2017-05       100.0  0.5  0.5  0.3  0.3  0.3  0.4  0.1
2017-06       100.0  0.5  0.4  0.4  0.3  0.4  0.4  0.2
2017-07       100.0  0.5  0.3  0.2  0.3  0.2  0.3  0.1
2017-08       100.0  0.7  0.3  0.3  0.3  0.5  0.3  0.3

In [39]:
plot_ret = retention.round(1).iloc[:, 1:13]
plot_ret.index = plot_ret.index.astype(str)

fig = px.imshow(plot_ret, text_auto=True, aspect="auto", title="Cohort Retention % (months after first purchase)")
fig.show(renderer="browser")

In [40]:
avg_ret = retention.iloc[:, 1:].mean().round(2)
avg_ret

months_since
1     0.48
2     0.34
3     0.25
4     0.29
5     0.23
6     0.26
7     0.21
8     0.21
9     0.17
10    0.26
11    0.21
12    0.21
13    0.17
14    0.15
15    0.15
16    0.14
17    0.24
19    0.14
20     NaN
dtype: float64

In [41]:
fig2 = px.line(x=avg_ret.index[:12], y=avg_ret.values[:12], markers=True,
               labels={"x": "Months since first purchase", "y": "Avg retention %"},
               title="Average Retention %")
fig2.show(renderer="browser")

In [42]:
retention.round(1).iloc[8:, :8]

months_since      0    1    2    3    4    5    6    7
cohort_month
2017-09       100.0  0.7  0.5  0.3  0.4  0.2  0.2  0.2
2017-10       100.0  0.7  0.3  0.1  0.2  0.2  0.2  0.4
2017-11       100.0  0.6  0.4  0.2  0.2  0.2  0.1  0.2
2017-12       100.0  0.2  0.3  0.3  0.3  0.2  0.2  0.0
2018-01       100.0  0.3  0.4  0.3  0.3  0.2  0.2  0.2
2018-02       100.0  0.3  0.4  0.3  0.3  0.2  0.2  NaN
2018-03       100.0  0.4  0.3  0.3  0.1  0.1  NaN  NaN
2018-04       100.0  0.6  0.3  0.2  0.1  NaN  NaN  NaN
2018-05       100.0  0.5  0.3  0.2  NaN  NaN  NaN  NaN
2018-06       100.0  0.4  0.3  NaN  NaN  NaN  NaN  NaN
2018-07       100.0  0.5  NaN  NaN  NaN  NaN  NaN  NaN
2018-08       100.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN

In [43]:
snapshot = df["order_purchase_timestamp"].max() + pd.Timedelta(days=1)
snapshot

Timestamp('2018-08-30 15:00:37')

In [47]:
rfm = df.groupby("customer_unique_id").agg(
    last_purchase=("order_purchase_timestamp", "max"),
    frequency=("order_id", "nunique"),
    monetary=("price", "sum")
)
rfm["recency"] = (snapshot - rfm["last_purchase"]).dt.days
rfm.head()

,last_purchase,frequency,monetary,recency
customer_unique_id,,,,
0000366f3b9a7992bf8c76cfdf3221e2,2018-05-10 10:56:27,1,129.90,112
0000b849f77a49e4a4ce2b2a4ca5be3f,2018-05-07 11:11:27,1,18.90,115
0000f46a3911fa3c0805444483337064,2017-03-10 21:05:03,1,69.00,537
0000f6ccb0745a6a4b88665a16c9f078,2017-10-12 20:29:41,1,25.99,321
0004aac84e0df4da2b147fca70cf8255,2017-11-14 19:45:42,1,180.00,288

In [2]:
import pandas as pd

In [4]:
import pandas as pd
import plotly.express as px

orders = pd.read_csv("data/olist_orders_dataset.csv")
items = pd.read_csv("data/olist_order_items_dataset.csv")
customers = pd.read_csv("data/olist_customers_dataset.csv")
products = pd.read_csv("data/olist_products_dataset.csv")
translation = pd.read_csv("data/product_category_name_translation.csv")

delivered = orders[orders["order_status"] == "delivered"]
df = pd.merge(delivered, items, on="order_id")
df = pd.merge(df, customers, on="customer_id")
df = pd.merge(df, products[["product_id", "product_category_name"]], on="product_id", how="left")
df = pd.merge(df, translation, on="product_category_name", how="left")
df["product_category_name_english"] = df["product_category_name_english"].fillna("unknown")

df["order_purchase_timestamp"] = pd.to_datetime(df["order_purchase_timestamp"])
df["Month"] = df["order_purchase_timestamp"].dt.to_period("M")

df["cohort_month"] = df.groupby("customer_unique_id")["order_purchase_timestamp"].transform("min").dt.to_period("M")
df["months_since"] = (df["Month"].dt.year - df["cohort_month"].dt.year) * 12 + (df["Month"].dt.month - df["cohort_month"].dt.month)

snapshot = df["order_purchase_timestamp"].max() + pd.Timedelta(days=1)
rfm = df.groupby("customer_unique_id").agg(
    last_purchase=("order_purchase_timestamp", "max"),
    frequency=("order_id", "nunique"),
    monetary=("price", "sum")
)
rfm["recency"] = (snapshot - rfm["last_purchase"]).dt.days

df.shape

(110197, 23)

In [5]:
rfm["R"] = pd.qcut(rfm["recency"], 5, labels=[5, 4, 3, 2, 1])
rfm["M"] = pd.qcut(rfm["monetary"], 5, labels=[1, 2, 3, 4, 5])
rfm["F"] = pd.cut(rfm["frequency"], bins=[0, 1, 2, float("inf")], labels=[1, 2, 3])
rfm.shape

(93358, 7)

In [6]:
rfm[["recency", "frequency", "monetary", "R", "F", "M"]].head(10)

                                  recency  frequency  monetary  R  F  M
customer_unique_id
0000366f3b9a7992bf8c76cfdf3221e2      112          1    129.90  4  1  4
0000b849f77a49e4a4ce2b2a4ca5be3f      115          1     18.90  4  1  1
0000f46a3911fa3c0805444483337064      537          1     69.00  1  1  2
0000f6ccb0745a6a4b88665a16c9f078      321          1     25.99  2  1  1
0004aac84e0df4da2b147fca70cf8255      288          1    180.00  2  1  5
0004bd2a26a76fe21f786e4fbd80607f      146          1    154.00  4  1  4
00050ab1314c0e55a6ca13cf7181fecf      132          1     27.99  4  1  1
00053a61a98854899e70ed204dd4bafe      183          1    382.00  3  1  5
0005e1862207bf6ccc02e4228effd9a0      543          1    135.00  1  1  4
0005ef4cd20d2893f0d9fbd94d3c0d97      170          1    104.90  4  1  3

In [7]:
rfm["R"] = rfm["R"].astype(int)
rfm["F"] = rfm["F"].astype(int)
rfm["M"] = rfm["M"].astype(int)
rfm["RFM_score"] = rfm["R"] + rfm["F"] + rfm["M"]
rfm[["R", "F", "M", "RFM_score"]].head()

                                  R  F  M  RFM_score
customer_unique_id
0000366f3b9a7992bf8c76cfdf3221e2  4  1  4          9
0000b849f77a49e4a4ce2b2a4ca5be3f  4  1  1          6
0000f46a3911fa3c0805444483337064  1  1  2          4
0000f6ccb0745a6a4b88665a16c9f078  2  1  1          4
0004aac84e0df4da2b147fca70cf8255  2  1  5          8

In [8]:
def segment(score):
    if score >= 12:
        return "Champions"
    elif score >= 9:
        return "Loyal"
    elif score >= 6:
        return "Potential"
    elif score >= 4:
        return "At Risk"
    else:
        return "Lost"

rfm["segment"] = rfm["RFM_score"].apply(segment)
rfm["segment"].value_counts()

segment
Potential    47171
Loyal        22642
At Risk      19072
Lost          4089
Champions      384
Name: count, dtype: int64

In [11]:
df.to_csv("data/cleaned_orders.csv", index=False)
rfm.to_csv("data/rfm_table.csv")